# -*- coding: utf-8 -*-
"""Lesson-01_Activity-01.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NGyN_l3CnN_TNNOlHg9ZiHgD-MnhSb8q
"""

print("Hello, I am TBot1.0! What is your name?")
name = input()

print(f"Nice meeting you, {name}!")

print("How are you feeling today?")
feeling = input()

if feeling.lower() == "good": print(f"I'm glad to hear that!")
elif feeling.lower() == "bad": print(f"I'm sorry to hear that.")
else: print("I understand.")

print(f"It was nice talking with you today, {name}!")